### PR TITLE
Fix : 100% load due to writer callback

### PR DESCRIPTION
**Pull request by bamthomas**
For serial device there is no need to wait for write availability

### CODE REVIEW

**Comment by bamthomas** [comment]
oups sorry for the broken build on flake8, when I ran the tests on my PC it was ok. ©works_on_my_computer

**Comment by d0ugal** [comment]
Seems reasonable, this can be merged once the build is fixed.

**Comment by RouquinBlanc** [comment]
Hi Bruno, I took your changes in my fork and confirm it works like a charm. 
Exit the 100% CPU loop!

**Comment by bamthomas** [comment]
Thank you Rouquin Blanc for your feedback. Yes I'm running it on a raspberry pi and since then the little machine is 99% idle

**Comment by d0ugal** [comment]
Thanks for the fix @bamthomas and your verification @RouquinBlanc!

**Comment by bamthomas** [comment]
Would it be possible to release a 0.4 or another tag  ?

**Comment by d0ugal** [comment]
Sure, I'll aim to do this tomorrow.

**Comment by bamthomas** [comment]
Thanks !

**Pull request merged**
