### PR TITLE
Adding the possibility to add coroutines as callbacks for AsyncioTransport

### PR DESCRIPTION
**Pull request by RouquinBlanc**
Hi D0ugal,

For my project I needed to pass a coroutine as a callback to the AsyncioTransport. Currently you can't execute coros as callback. Could you please consider taking those changes in?

It's a great lib!

Cheers
Jonathan

### CODE REVIEW

**Comment by d0ugal** [comment]
Would you be able to add a usage example to the README?

**Comment by RouquinBlanc** [comment]
Hi D0ugal, you are absolutely right. Added a small example. As Bruno mentioned, and if you wish to take those changes in, it would be great to increase the version number.

Thanks
Jonathan

**Comment by d0ugal** [comment]
Merged. I'll try and do a release this weekend. Feel free to remind me on Monday if I don't get around to it.

**Comment by RouquinBlanc** [comment]
Thanks a lot!

**Comment by d0ugal** [comment]
Released.

**Comment by RouquinBlanc** [comment]
Thanks a lot!

**Pull request merged**
